In [1]:
import numpy as np

MOD = 7  # Trabajamos sobre Z_7

def mod_mat_inv(A, mod):
    """Calcula la inversa modular de una matriz cuadrada sobre Z_mod."""
    det = int(round(np.linalg.det(A))) % mod
    det_inv = pow(det, -1, mod)
    adj = np.round(det * np.linalg.inv(A)).astype(int) % mod
    return (det_inv * adj) % mod

def conjugate(x, g):
    """Conjugación g^x = x⁻¹ g x en Z_mod."""
    x_inv = mod_mat_inv(x, MOD)
    return x_inv @ g @ x % MOD

def commutator(x, y):
    """Conmutador [x, y] = x⁻¹ y⁻¹ x y"""
    x_inv = mod_mat_inv(x, MOD)
    y_inv = mod_mat_inv(y, MOD)
    return x_inv @ y_inv @ x @ y % MOD

# ========== 1. MATRICES PÚBLICAS ==========
A1 = np.array([[1, 1, 0], [0, 1, 0], [0, 0, 1]])
A2 = np.array([[1, 0, 0], [0, 1, 1], [0, 0, 1]])
A3 = np.array([[1, 0, 1], [0, 1, 0], [0, 0, 1]])

B1 = np.array([[1, 0, 0], [1, 1, 0], [0, 0, 1]])
B2 = np.array([[1, 0, 0], [0, 1, 0], [1, 0, 1]])
B3 = np.array([[1, 0, 0], [0, 1, 0], [0, 1, 1]])

# ========== 2. CLAVES PRIVADAS ==========
x = A2 @ mod_mat_inv(A3, MOD) @ A1 % MOD  # Alice
y = mod_mat_inv(B1, MOD) @ B3 % MOD       # Bob

# ========== 3. INTERCAMBIO DE CONJUGADOS ==========
B1_conj = conjugate(x, B1)
B2_conj = conjugate(x, B2)
B3_conj = conjugate(x, B3)

A1_conj = conjugate(y, A1)
A2_conj = conjugate(y, A2)
A3_conj = conjugate(y, A3)

# ========== 4. CÁLCULO DE LA CLAVE COMPARTIDA ==========
K_alice = commutator(x, y)
K_bob = commutator(x, y)  # Debe ser igual

# ========== 5. MOSTRAR RESULTADOS ==========
print("\n=== MATRICES PÚBLICAS ===")
print("A1:\n", A1)
print("A2:\n", A2)
print("A3:\n", A3)
print("B1:\n", B1)
print("B2:\n", B2)
print("B3:\n", B3)

print("\n=== CLAVES PRIVADAS ===")
print("Clave privada de Alice (x):\n", x)
print("Clave privada de Bob (y):\n", y)

print("\n=== CONJUGADOS ENVIADOS ===")
print("B1^x:\n", B1_conj)
print("B2^x:\n", B2_conj)
print("B3^x:\n", B3_conj)
print("A1^y:\n", A1_conj)
print("A2^y:\n", A2_conj)
print("A3^y:\n", A3_conj)

print("\n=== CLAVE COMPARTIDA ===")
print("Clave compartida de Alice:\n", K_alice)
print("Clave compartida de Bob:\n", K_bob)
print("¿Las claves coinciden?:", np.array_equal(K_alice, K_bob))


=== MATRICES PÚBLICAS ===
A1:
 [[1 1 0]
 [0 1 0]
 [0 0 1]]
A2:
 [[1 0 0]
 [0 1 1]
 [0 0 1]]
A3:
 [[1 0 1]
 [0 1 0]
 [0 0 1]]
B1:
 [[1 0 0]
 [1 1 0]
 [0 0 1]]
B2:
 [[1 0 0]
 [0 1 0]
 [1 0 1]]
B3:
 [[1 0 0]
 [0 1 0]
 [0 1 1]]

=== CLAVES PRIVADAS ===
Clave privada de Alice (x):
 [[1 1 6]
 [0 1 1]
 [0 0 1]]
Clave privada de Bob (y):
 [[1 0 0]
 [6 1 0]
 [0 1 1]]

=== CONJUGADOS ENVIADOS ===
B1^x:
 [[0 6 1]
 [1 2 6]
 [0 0 1]]
B2^x:
 [[3 2 5]
 [6 0 1]
 [1 1 0]]
B3^x:
 [[1 2 2]
 [0 0 6]
 [0 1 2]]
A1^y:
 [[0 1 0]
 [6 2 0]
 [1 6 1]]
A2^y:
 [[1 0 0]
 [0 2 1]
 [0 6 0]]
A3^y:
 [[1 1 1]
 [0 2 1]
 [0 6 0]]

=== CLAVE COMPARTIDA ===
Clave compartida de Alice:
 [[3 3 1]
 [5 3 6]
 [1 6 1]]
Clave compartida de Bob:
 [[3 3 1]
 [5 3 6]
 [1 6 1]]
¿Las claves coinciden?: True
